### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by Luthetus** [Luthetus/Luthetus.Ide#279]
# Common
- [ ] TreeView type letter 'r' go to 'r' nodes
- [ ] When rendering a notification, allow a 'measurement' step to determine a size for the notification. When rendering many stop once they go off screen
- [ ] { Alt + v } should not type into the text editor.
- [ ] { Ctrl + Tab } pick context should set focus.
    - [ ] Consider what happens when the picked context isn't part of a panel group.
- [ ] Firefox fixes
    - [ ] ResizeableRow
    - [ ] PanelTabs (the vertical text)
- [ ] Mobile fixes
    - [ ] Combine left and right panels when width < ?

# Text Editor
- [ ] Drag tab off fatal exception bad
- [ ] The autocomplete from one view model carried over to another view model and only went away when I went back to the first view model and hit escape.
- [ ] Open file in code search first time before in main editor does view model get shared if then open in main editor?
- [ ] Scroll while content fit screen see bottom right scrollbar connect become less opaque break mouse event ?
- [ ] As a test: Delete in DotNetSolutionIdeApi.cs all of the class body and see if the open and closing curly brace of the class definition THEN undo and see if its undone properly.
- [ ] Mobile fixes
    - [ ] Better support for editing text on mobile

# Ide
- [ ] For ServerSide, OnInitializedAsync results in JavaScript running before component is ready due to multithreading
- [ ] Scrolling of the terminal is frustrating.
- [ ] Clear terminal based on text length rather than command count

# Extensions.Git
- [ ] When drawing diff presentation layer, if the changed file has any collapsed lines (contiguous unchanged lines) then the current naive implementation won't draw the background color on the correct line.

# Extensions.DotNet
- [ ] Multi solution, and when including a solution or excluding it add or remove the compiler service data for that solution.
